version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: zoneminderhq/zoneminder:1.36-ubuntu18.04
        restart: unless-stopped
        ports:
            - 7878:80
            - "30200-30300:30200-30300"
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            # - TZ=${TZ:-America/Los_Angeles}
            - "TZ=Asia/Shanghai"
        volumes:
            - "./volumes_test/events:/var/cache/zoneminder/events"
            - "./volumes_test/images:/var/cache/zoneminder/images"
            - "./volumes_test/mysql:/var/lib/mysql"
            - "./volumes_test/logs:/var/log/zoneminder"
            - "./ports.conf:/etc/apache2/ports.conf"
            - "./000-default.conf:/etc/apache2/sites-available/000-default.conf"

# volumes:
#   events:
#   images:
#   mysql:
#   logs:
