version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: zoneminderhq/zoneminder:1.36-ubuntu18.04
        restart: unless-stopped
        ports:
            - 7878:80
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-America/Los_Angeles}
        volumes:
            - "./volumes/events:/var/cache/zoneminder/events"
            - "./volumes/images:/var/cache/zoneminder/images"
            - "./volumes/mysql:/var/lib/mysql"
            - "./volumes/logs:/var/log/zm"

# volumes:
#   events:
#   images:
#   mysql:
#   logs:
