version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: zoneminderhq/zoneminder:1.36-ubuntu18.04
        restart: unless-stopped
        ports:
            - 7878:80
        network_mode: "bridge"
        privileged: true
        shm_size: 512M
        environment:
            - TZ=${TZ:-America/Los_Angeles}
        volumes:
            - "./volumes_1.36/events:/var/cache/zoneminder/events"
            - "./volumes_1.36/images:/var/cache/zoneminder/images"
            - "./volumes_1.36/mysql:/var/lib/mysql"
            - "./volumes_1.36/logs:/var/log/zoneminder"
            - "./volumes_1.36/logs_zm:/var/log/zm"

# volumes:
#   events:
#   images:
#   mysql:
#   logs:
